services:
  outlinkedserver:
    image: outlinkedserver
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    build:
      context: OutLinkedServer
      dockerfile: OutLinkedServer/Dockerfile
    ports:
      - 8888:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
  outlinkedclient:
    image: outlinkedclient
    build:
      context: outlinked-client
      dockerfile: Dockerfile
    depends_on:
      - outlinkedserver
    ports:
      - 80:8080
    environment:
      NODE_ENV: docker
